# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: JEST Report

on:
  push:
    branches:
      - main
      - develop

jobs:
  check:  
    name: report
    runs-on: macos-latest
    steps:
    - uses: RedaktionsNetzwerk-Deutschland/action-jest-reporter@v1.0.0
        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE: ${{ github.event.issue.html_url }}
  
